version: "3.7"
services:
  devops-db:
    hostname: devops-db
    container_name: devops-db
    image: mysql:8.0.33
    restart: always
    volumes:
      - ./mydb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_password
      - db_root_password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  devops-rest:
    hostname: devops-rest
    container_name: devops-rest
    image: toby4all/tobby_pipeline:${IMAGE_TAG}
    depends_on:
      devops-db:
        condition: service_healthy
    environment:
      db_host: devops-db
      db_port: 3306
      db_user: user
      db_pass: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "5000:5000"
    expose:
      - "5000"
    healthcheck:
      test: curl --fail http://localhost:5000/users/1 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt

volumes:
    mydb:



